ser:ser.c pack.c cli_link.c user_mysql.c user.c experiment.c ser.h pack.h cli_link.h user_mysql.h user.h experiment.h
	gcc ser.c pack.c cli_link.c user_mysql.c user.c experiment.c -o ser -Wall -lmysqlclient -g

clean:
	rm ser
